version: "3.9"

services:
  redis:
    image: redis:7.0.2
    command: redis-server --save 60 1 --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
  rabbitmq:
    image: rabbitmq:3.10.5-management
    ports:
      - 5672:5672
      - 15672:15672

