micronaut:
  application:
    name: ghostfolioTrading212Import
  http:
    client:
      read-timeout: 60s
netty:
  default:
    allocator:
      max-order: 3

redis:
  uri: redis://localhost
  io-thread-pool-size: 5
  computation-thread-pool-size: 4
